### PR TITLE
To authorize executeBatch by token parameter

### PR DESCRIPTION
**Pull request by andreaValenzi**
I fixed the batch execution in case of added batch requests have a token parameter.
It takes token parameter by first request added.
Without this change the batch execution returns 401 error.

### CODE REVIEW

**Comment by AleksandrRogov** [comment]
hi @andreaValenzi, thank you for the pull request. I did not think of this scenario.

the problem i see here is what if the token is already expired when the batch request is finally executed? or what if the first request does not have a token but the second does?

the only solution i see here is to add a request parameter to `executeBatch` function to allow user to specify a token. other than that for now developer can use `setConfig` function as a workaround to setting a token for batch request.

**Comment by andreaValenzi** [comment]
Hi @AleksandrRogov ,

I agree with you,
I've done the changes to have request parameter to executeBatch.
Let me know what you think about it.

Thanks,
Andrea

**Comment by AleksandrRogov** [comment]
@andreaValenzi this looks good. only the code needs to be in ES5 :) and tests need to cover new parameter. this is just so you know, i can do it myself when i merge this PR.

**Comment by andreaValenzi** [comment]
@AleksandrRogov done :)

**Comment by andreaValenzi** [comment]
I forgot this one: https://github.com/AleksandrRogov/DynamicsWebApi/pull/74/commits/27dd081df379d7c073f7ca909779d4f5b6c2ffc1

sorry

**Comment by andreaValenzi** [comment]
and this one: https://github.com/AleksandrRogov/DynamicsWebApi/pull/74/commits/10626fa2bccc5d6bc0cf465e28c4ee27ed121684

😅

**Comment by AleksandrRogov** [comment]
Thanks @andreaValenzi ! Much appreciated!

**Pull request merged**
