### PR TITLE
AAD Impersonation

### PR DESCRIPTION
**Pull request by azakariaMSFT**
Thank you for keeping this library awesome!

 - Fix impersonate documentation string where it is mixed with webApiUrl
 - Introduce an impersonateAAD option for the new preferred way for impersonating a user via an azure object id directly from the auth claims 
**Preferred**: Impersonate a user based on their Azure Active Directory (AAD) object id by passing that value along with the header CallerObjectId.
docs: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/impersonate-another-user-web-api

mimicked over MSCRMCallerID which accepts a systemuserid
Tested via a nodejs server (not included) that uses an application id to authenticate and takes the user aad object id directly from the passport authInfo

### CODE REVIEW

**Comment by AleksandrRogov** [comment]
@azakariaMSFT that's awesome! thanks for the PR. It would be even more awesome if you could add additional tests for the new functionality. If not, let me know I will add them later myself.

Thanks so much!

**Comment by azakariaMSFT** [comment]
absolutely, I'm working on those tests now.

**Comment by AleksandrRogov** [comment]
@azakariaMSFT awesome! thank you!

**Comment by azakariaMSFT** [comment]
Thanks, What is the cadence for releasing an update on npm?

**Comment by AleksandrRogov** [comment]
@azakariaMSFT I'll release it in the morning (September 8).

**Pull request merged**
